/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import static jFrame.Forget1.name1;
import java.sql.*;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Anand
 */
public class Forget extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public Forget() {
        initComponents();
        Section();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void Section() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("book.png")));
    }

    public void Check() {
        String nam = lbl_username.getText();
        String em = lbl_email.getText();
        Connection con = null;
        PreparedStatement prt = null;

        try {
            con = DbConnection.getConnection();
            prt = con.prepareStatement("select * from users where name = ? and email = ?");

            prt.setString(1, nam);
            prt.setString(2, em);
            ResultSet rs = (ResultSet) prt.executeQuery();

            if (rs.next()) {
                String name = rs.getString("name");
                String email = rs.getString("email");

                if (nam.equals(name) || em.equals(email)) {
                    JOptionPane.showMessageDialog(this, "Correct Username and Email ");
                     Showname();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username or Email");
                new Forget().setVisible(true);
            }
            rs.close();
            prt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void Showname() {
        try {
            Connection con = DbConnection.getConnection();
            String sql = "select * from users where name = '" + lbl_username.getText() + "' ";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                name1.setText(rs.getString(2));
                new Forget1().setVisible(true);
            } else {
                System.out.println("Error");
            }
            rs.close(); 
            con.close();
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 306));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 20, 270, -1));

        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 23, 69, -1));

        jLabel3.setText("Email:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 60, -1, -1));

        lbl_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_emailKeyPressed(evt);
            }
        });
        jPanel2.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 57, 270, -1));

        btn_reset.setText("Reset");
        btn_reset.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_resetMouseMoved(evt);
            }
        });
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 70, 27));

        btn_check.setText("Check");
        btn_check.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_checkMouseMoved(evt);
            }
        });
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        btn_check.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_checkKeyPressed(evt);
            }
        });
        jPanel2.add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 70, 27));

        btn_exit.setText("Exit");
        btn_exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_exitMouseMoved(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 70, 27));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 420, 170));

        jPanel3.setBackground(new java.awt.Color(241, 196, 15));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forget Password");
        jLabel1.setAlignmentY(0.0F);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 420, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        Forget page = new Forget();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        Check();
        this.dispose();
    }//GEN-LAST:event_btn_checkActionPerformed

    private void btn_checkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkMouseMoved
        btn_check.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkMouseMoved

    private void btn_resetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseMoved
        btn_reset.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetMouseMoved

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseMoved
        btn_exit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_exitMouseMoved

    private void lbl_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Check();
            this.dispose();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_lbl_emailKeyPressed

    private void btn_checkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_checkKeyPressed
        Check();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lbl_email;
    private javax.swing.JTextField lbl_username;
    // End of variables declaration//GEN-END:variables
}
