/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Anand
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        Section();
    }

    //methods to insert values into user table
    public void insertSignupDetails() {
        String name = txt_username.getText();
        String password = txt_password.getText();

        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());

        String email = jCTextField19.getText();
        String contact = jCTextField2.getText();
        Connection con = null;
        PreparedStatement prt = null;

        try {
            con = (Connection) DbConnection.getConnection();
            String sql = "insert into users(name,email,contact,password_hash) values(?,?,?,?)";
            prt = con.prepareStatement(sql);

            prt.setString(1, name);
            prt.setString(2, email);
            prt.setString(3, contact);
            prt.setString(4, hashedPassword);

            int insertRowCount = prt.executeUpdate();
            if (insertRowCount > 0) {
                JOptionPane.showMessageDialog(this, "SignUp Successfully");
                LoginPage page = new LoginPage();
                page.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "SignUp Failure");

            }
            con.close();
            prt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }

//    hash password 
    // Validation
    public boolean validateSignup() {
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        String email = jCTextField19.getText();
        String contact = jCTextField2.getText();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Username");
            return false;
        } else if (pwd.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Password");
            return false;
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Valid Email");
            return false;
        } else if (contact.equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Contact Number");
            return false;
        } else {
            return true;
        }

    }

    //check duplicate users
    public boolean checkDuplicateUser() {
        String name = txt_username.getText();
        boolean isExist = false;
        try {
            Connection con = DbConnection.getConnection();

            PreparedStatement prt = con.prepareStatement("select * from users where name = ?");
            prt.setString(1, name);

            ResultSet rs = (ResultSet) prt.executeQuery();
            if (rs.next()) {
                isExist = true;
            } else {
                isExist = false;
            }
            con.close();
            prt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return isExist;

    }

    private void Section() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("book.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jCTextField19 = new app.bolivia.swing.JCTextField();
        jLabel45 = new javax.swing.JLabel();
        btn_signUp = new rojerusan.RSMaterialButtonCircle();
        jLabel10 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        rSMaterialButtonCircle3 = new rojerusan.RSMaterialButtonCircle();
        view = new javax.swing.JCheckBox();
        btn_login = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Advance Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 250, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Welcome To");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 170, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/signup-library-icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 690));

        jToolBar1.setRollover(true);
        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 704));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, 50));

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Create New Account Here");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, -1));

        txt_username.setBackground(new java.awt.Color(102, 102, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txt_username.setPlaceholder("Enter Username");
        jPanel3.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 380, -1));

        jLabel9.setBackground(new java.awt.Color(255, 51, 51));
        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, 40));

        jCTextField2.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextField2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jCTextField2.setPlaceholder("Enter Mobile Number");
        jCTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCTextField2KeyTyped(evt);
            }
        });
        jPanel3.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 380, -1));

        jLabel22.setBackground(new java.awt.Color(255, 51, 51));
        jLabel22.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Contact");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 270, 40));

        jLabel23.setBackground(new java.awt.Color(255, 51, 51));
        jLabel23.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 50, 50));

        jLabel42.setBackground(new java.awt.Color(255, 51, 51));
        jLabel42.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 50));

        jLabel43.setBackground(new java.awt.Color(255, 51, 51));
        jLabel43.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Password");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 270, 40));

        jLabel44.setBackground(new java.awt.Color(255, 51, 51));
        jLabel44.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 50));

        jCTextField19.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jCTextField19.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jCTextField19.setPlaceholder("Enter Email");
        jPanel3.add(jCTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 380, -1));

        jLabel45.setBackground(new java.awt.Color(255, 51, 51));
        jLabel45.setFont(new java.awt.Font("Sylfaen", 0, 20)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Email");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 270, 40));

        btn_signUp.setBackground(new java.awt.Color(255, 51, 51));
        btn_signUp.setText("SIGNIUP");
        btn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpActionPerformed(evt);
            }
        });
        btn_signUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_signUpKeyPressed(evt);
            }
        });
        jPanel3.add(btn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 360, 70));

        jLabel10.setBackground(new java.awt.Color(255, 51, 51));
        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Signup Page");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 170, -1));

        txt_password.setBackground(new java.awt.Color(102, 102, 255));
        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel3.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 380, -1));

        rSMaterialButtonCircle3.setText("X");
        rSMaterialButtonCircle3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        rSMaterialButtonCircle3.setPreferredSize(new java.awt.Dimension(80, 60));
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        jPanel3.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View Password");
        view.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                viewMouseMoved(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel3.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, 30));

        btn_login.setBackground(new java.awt.Color(0, 0, 204));
        btn_login.setText("LOGIN");
        btn_login.setMaximumSize(new java.awt.Dimension(96, 28));
        btn_login.setMinimumSize(new java.awt.Dimension(96, 28));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        btn_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_loginKeyPressed(evt);
            }
        });
        jPanel3.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 360, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 520, 700));

        setSize(new java.awt.Dimension(1300, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpActionPerformed
        if (validateSignup() == true) {
            if (checkDuplicateUser() == false) {
                insertSignupDetails();
//                nameshow();

            } else {
                JOptionPane.showMessageDialog(this, "Username Already Exist ");
            }
        }
    }//GEN-LAST:event_btn_signUpActionPerformed

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Exit Program?", "EXIT", JOptionPane.YES_NO_OPTION);
        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // show Password code here:
        if (view.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_viewActionPerformed

    private void viewMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseMoved
        view.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
// TODO add your handling code here:
    }//GEN-LAST:event_viewMouseMoved

    private void jCTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCTextField2KeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || jCTextField2.getText().length() >= 10) {
            evt.consume();
        } // only enter the number
    }//GEN-LAST:event_jCTextField2KeyTyped

    private void jCTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (validateSignup() == true) {
                if (checkDuplicateUser() == false) {
                    insertSignupDetails();
//                nameshow();

                } else {
                    JOptionPane.showMessageDialog(this, "Username Already Exist ");
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2KeyPressed

    private void btn_signUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_signUpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (validateSignup() == true) {
                if (checkDuplicateUser() == false) {
                    insertSignupDetails();
//                nameshow();

                } else {
                    JOptionPane.showMessageDialog(this, "Username Already Exist ");
                }
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_btn_signUpKeyPressed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyPressed
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle btn_login;
    private rojerusan.RSMaterialButtonCircle btn_signUp;
    private app.bolivia.swing.JCTextField jCTextField19;
    private app.bolivia.swing.JCTextField jCTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private javax.swing.JPasswordField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    private javax.swing.JCheckBox view;
    // End of variables declaration//GEN-END:variables
}
