/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Anand
 */
public class StudentPrint extends javax.swing.JFrame {

    /**
     * Creates new form StudentPrint
     */
    DefaultTableModel model;

    public StudentPrint() {
        initComponents();
        AllStudentDetails();
        Section();
    }

    public void searchByE() {
        String name = txt_sbn.getText();

        try {
            Connection con = DbConnection.getConnection();
            String sql = "select * from students where aadhaar = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, name);
//            pst.setString(2, Branch);

            ResultSet rs = pst.executeQuery();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            clearTable();

            while (rs.next()) {
                String studentId = rs.getString("student_id");
                String studentName = rs.getString("student_name");
                String phone = rs.getString("phone_number");
                String Address = rs.getString("address");
                String aadhaar = rs.getString("aadhaar");
                String enrollDate = rs.getLong("enroll_date") > 0 ? sdf.format(new java.sql.Date(rs.getLong("enroll_date"))) : "N/A";
                String expiryDate = rs.getLong("expiry_date") > 0 ? sdf.format(new java.sql.Date(rs.getLong("expiry_date"))) : "N/A";
                String ibn = rs.getString("issue_book_no");

                Object[] obj = {studentId, studentName, phone, Address, aadhaar, enrollDate, expiryDate, ibn};
                model = (DefaultTableModel) table_StudentDetails.getModel();
                model.addRow(obj);
            }
            rs.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

// Find all record of the student....
    public void AllStudentDetails() {
        try {
            Connection con = DbConnection.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from students ";
            ResultSet rs = st.executeQuery(sql);
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            while (rs.next()) {
                String studentId = rs.getString("student_id");
                String studentName = rs.getString("student_name");
                String phone = rs.getString("phone_number");
                String Address = rs.getString("address");
                String aadhaar = rs.getString("aadhaar");
                String enrollDate = rs.getLong("enroll_date") > 0 ? sdf.format(new Date(rs.getLong("enroll_date"))) : "N/A";
                String expiryDate = rs.getLong("expiry_date") > 0 ? sdf.format(new Date(rs.getLong("expiry_date"))) : "N/A";
                String ibn = rs.getString("issue_book_no");

                Object[] obj = {studentId, studentName, phone, Address, aadhaar, enrollDate, expiryDate, ibn};
                model = (DefaultTableModel) table_StudentDetails.getModel();
                model.addRow(obj);
            }
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) table_StudentDetails.getModel();
        model.setRowCount(0);
    }

    private void Section() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("book.png")));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_StudentDetails = new rojeru_san.complementos.RSTableMetro();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSMaterialButtonCircle6 = new rojerusan.RSMaterialButtonCircle();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBtnPrint = new javax.swing.JButton();
        jBtnSearch = new javax.swing.JButton();
        txt_sbn = new app.bolivia.swing.JCTextField();
        id_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        Enroll = new javax.swing.JLabel();
        Expiry = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rSMaterialButtonCircle5 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_StudentDetails.setAutoCreateRowSorter(true);
        table_StudentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Phone No", "Address", "Aadhaar", "Enroll Date", "Expiry Date", "No of Book"
            }
        ));
        table_StudentDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        table_StudentDetails.setDropMode(javax.swing.DropMode.ON);
        table_StudentDetails.setFocusable(false);
        table_StudentDetails.setGridColor(new java.awt.Color(255, 255, 255));
        table_StudentDetails.setInheritsPopupMenu(true);
        table_StudentDetails.setRowHeight(40);
        table_StudentDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_StudentDetailsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_StudentDetails);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 950, 520));

        kGradientPanel1.setInheritsPopupMenu(true);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(150);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonCircle6.setText("X");
        rSMaterialButtonCircle6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        rSMaterialButtonCircle6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle6MouseClicked(evt);
            }
        });
        kGradientPanel1.add(rSMaterialButtonCircle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 80, 70));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Student_Male_100px.png"))); // NOI18N
        jLabel1.setText("CREATE STUDENTS Id");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 450, -1));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 355, 3));

        jBtnPrint.setBackground(new java.awt.Color(153, 153, 255));
        jBtnPrint.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jBtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/Printer.png"))); // NOI18N
        jBtnPrint.setAlignmentY(0.0F);
        jBtnPrint.setBorder(null);
        jBtnPrint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnPrintMouseMoved(evt);
            }
        });
        jBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrintActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jBtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 50, 50));

        jBtnSearch.setBackground(new java.awt.Color(102, 102, 255));
        jBtnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnSearchMouseMoved(evt);
            }
        });
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });
        jBtnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnSearchKeyPressed(evt);
            }
        });
        kGradientPanel1.add(jBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 80, 30));

        txt_sbn.setBackground(new java.awt.Color(102, 102, 255));
        txt_sbn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_sbn.setAlignmentY(1.0F);
        txt_sbn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_sbn.setPlaceholder("Search By Aadhaar...");
        txt_sbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sbnKeyTyped(evt);
            }
        });
        kGradientPanel1.add(txt_sbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 150, 30));

        id_panel.setBackground(new java.awt.Color(204, 204, 255));
        id_panel.setPreferredSize(new java.awt.Dimension(310, 704));
        id_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("IDENTITY CARD");
        id_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 20, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/100000000.png"))); // NOI18N
        id_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ExpiryDate");
        id_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Id");
        id_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Name");
        id_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("MobileNo.");
        id_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("EnrollDate");
        id_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_panel.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 20));

        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_panel.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 20));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_panel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 20));

        Enroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_panel.add(Enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 20));

        Expiry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id_panel.add(Expiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText(":");
        id_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 10, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText(":");
        id_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 10, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText(":");
        id_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 10, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText(":");
        id_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 10, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText(":");
        id_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 10, -1));

        kGradientPanel1.add(id_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 324, 204));

        rSMaterialButtonCircle5.setText("<<");
        rSMaterialButtonCircle5.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        rSMaterialButtonCircle5.setPreferredSize(new java.awt.Dimension(80, 60));
        rSMaterialButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rSMaterialButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 704));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1300, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle5ActionPerformed
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle5ActionPerformed

    private void rSMaterialButtonCircle6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle6MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle6MouseClicked

    private void jBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrintActionPerformed
        try {
            // Create a JFileChooser to allow the user to select where to save the image
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Save Image As");
            fileChooser.setApproveButtonText("Save");
            fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            fileChooser.setAcceptAllFileFilterUsed(false); // Disables the "All files" option to avoid confusion

            // Set default file extension to .jpg
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("JPG Image", "jpg"));

            // Show the Save dialog
            int userSelection = fileChooser.showSaveDialog(null);
            
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                // Get the selected file path
                File fileToSave = fileChooser.getSelectedFile();
                
                // Check if the file doesn't already have a .jpg extension
                String filePath = fileToSave.getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".jpg")) {
                    filePath += ".jpg";  // Add .jpg extension if not present
                }

                // Create the BufferedImage (Assuming id_panel is your JPanel or any component to capture image from)
                BufferedImage image = new BufferedImage(id_panel.getWidth(), id_panel.getHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D g2d = image.createGraphics();
                id_panel.paint(g2d);
                g2d.dispose();

                // Save the image in JPG format to the selected location
                ImageIO.write(image, "jpg", new File(filePath));

                // Show confirmation message
                JOptionPane.showMessageDialog(null, "Image saved successfully: " + filePath);
            } else {
                JOptionPane.showMessageDialog(null, "No file selected. Image not saved.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saving image: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnPrintActionPerformed

    private void jBtnPrintMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPrintMouseMoved
        jBtnPrint.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPrintMouseMoved

    private void jBtnSearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSearchMouseMoved
        jBtnSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));   // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSearchMouseMoved

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        searchByE();
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void txt_sbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sbnKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txt_sbn.getText().length() >= 12) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sbnKeyTyped

    private void jBtnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnSearchKeyPressed
        searchByE();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSearchKeyPressed

    private void table_StudentDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_StudentDetailsMouseClicked
        // TODO add your handling code here:
        int rowNo = table_StudentDetails.getSelectedRow();
        TableModel model = table_StudentDetails.getModel();

        id.setText(model.getValueAt(rowNo, 0).toString());
        name.setText(model.getValueAt(rowNo, 1).toString());
        phone.setText(model.getValueAt(rowNo, 2).toString());
//        Txt_Aadhaar.setText(model.getValueAt(rowNo, 3).toString());
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date enrollDate = sdf.parse(model.getValueAt(rowNo, 5).toString());
            java.util.Date expiryDate = sdf.parse(model.getValueAt(rowNo, 6).toString());

            Enroll.setText(sdf.format(enrollDate));
            Expiry.setText(sdf.format(expiryDate));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_table_StudentDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPrint.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPrint.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPrint.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPrint.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enroll;
    private javax.swing.JLabel Expiry;
    private javax.swing.JLabel id;
    private javax.swing.JPanel id_panel;
    private javax.swing.JButton jBtnPrint;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle5;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle6;
    private rojeru_san.complementos.RSTableMetro table_StudentDetails;
    private app.bolivia.swing.JCTextField txt_sbn;
    // End of variables declaration//GEN-END:variables
}
